/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:e33a52e7-cd36-42ac-be27-58562d34c5ff",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_TGajVUJ2y",
    "aws_user_pools_web_client_id": "1cuda7qimu6dhv7roj8okhhmo",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://xsgoa2ojufewlgajn5koccfddq.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-t3jpe24bu5ffdmv3nvsb4asb2y"
};


export default awsmobile;
